### ISSUE TITLE
Afbeelding bestandsnamen en alt

### ISSUE THREAD

**Issue by Khdulkadir** [EBok1/the-startup-responsive-interactieve-website#14]
Geef je afbeeldingen duidelijkere bestandsnamen, en waar mogelijk een alt naam. 

https://github.com/EBok1/the-startup-responsive-interactieve-website/blob/679a8bcf9858f30e9ddfc1a7282b3997282ac257/index.html#L27

**Comment by EBok1** [comment]
Opgelost op deze manier:
``<img src="./logo.png" alt="Backbase logo">``
