### ISSUE TITLE
Script link in html onderaan body zetten

### ISSUE THREAD

**Issue by Khdulkadir** [EBok1/the-startup-responsive-interactieve-website#15]
https://github.com/EBok1/the-startup-responsive-interactieve-website/blob/679a8bcf9858f30e9ddfc1a7282b3997282ac257/index.html#L15

Zet je link die verwijst naar je javascript in je html onderaan de body voor een snellere laadtijd van je pagina.

**Comment by EBok1** [comment]
Met defer zorg ik er voor dat de javascript altijd als laatst laad, daarom zet ik hem niet onderaan.
