### ISSUE TITLE
tip voor de tekst 

### ISSUE THREAD

**Issue by rileyesther** [EBok1/the-startup-responsive-interactieve-website#2]
Misschien is het een idee dat als een tekst vrij lang is die in te korten doormiddel van puntjes. Mocht de gebruiker dan op die puntjes klikken expand de tekst en kan de gebruiker het in het geheel lezen.

**Comment by EBok1** [comment]
Je lees een kort stukje tekst. Je kunt meer lezen door op de tekst te klikken
