### ISSUE TITLE
Beetje padding op je 'product-line' class

### ISSUE THREAD

**Issue by Siem-P** [EBok1/the-startup-responsive-interactieve-website#5]
https://github.com/EBok1/the-startup-responsive-interactieve-website/blob/679a8bcf9858f30e9ddfc1a7282b3997282ac257/style.css#L75-L80

De border radius loopt een beetje door je tekst heen. 

Misschien kan je door een beetje extra padding toe te voegen aan deze class de de ruimte om de tekst iets groter maken.

Zie de bron voor een beetje extra uitleg -> https://developer.mozilla.org/en-US/docs/Web/CSS/padding

**Comment by EBok1** [comment]
Margin en padding toegevoegd.
