### ISSUE TITLE
Let op leesbaarheid van je bestanden - probeer te formatteren.

### ISSUE THREAD

**Issue by Siem-P** [EBok1/the-startup-responsive-interactieve-website#6]
In -> [Index.html](https://github.com/EBok1/the-startup-responsive-interactieve-website/blob/main/index.html) is de leesbaarheid van je HTML niet heel erg duidelijk.

Probeer eens een formatter uit.

Voorbeelden van een formatter die ik gebruik en erg handig is. Er zijn nog super veel andere mogelijkheden met deze formatter. Maar dat ga je later in de opleiding leren.

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by EBok1** [comment]
Geprobeerd duidelijker te maken. 
Voorbeeld: 
https://github.com/EBok1/the-startup-responsive-interactieve-website/blob/f50297567d69d0f8b5844e701d92b54b994dad6a/index.html#L77-L94
