### ISSUE TITLE
Linkjes hebben geen duidelijke manier van linking.

### ISSUE THREAD

**Issue by driezie** [EBok1/the-startup-responsive-interactieve-website#7]
https://github.com/EBok1/the-startup-responsive-interactieve-website/blob/679a8bcf9858f30e9ddfc1a7282b3997282ac257/index.html#L58
https://github.com/EBok1/the-startup-responsive-interactieve-website/blob/679a8bcf9858f30e9ddfc1a7282b3997282ac257/index.html#L89

> Let op de voorbeelden die ik hier geef zijn niet alle regels die ik bedoel. Deze zitten in elke item in de lijst/grid die je laat zien

Bij je link kan je niet naar een pagina om die "view docs" te openen. Ook heb je een "Download" knop maar deze is gewoon een `<p>` tag. 

Probeer een `<a href="">view docs<a>` en een <button>Download</button> te gebruiken met een `<form>` tag ervoor die linkt naar een bestand.

**Bronnen om eventueveel te gebruiken:**
- [4.6.5 Downloading resources](https://html.spec.whatwg.org/multipage/links.html#downloading-resources)
- [w3s | How TO - Download Link](https://arc.net/l/quote/uujiguls)

Groetjes,
Jelte :)

**Comment by EBok1** [comment]
Opgelost op deze manier:
``<a class="text-link" href="#">View docs</a>``
Ik heb geen bestand waar ik ze aan kan linken.
