### ISSUE TITLE
p element in button?

### ISSUE THREAD

**Issue by RukiyaTossou** [EBok1/the-startup-responsive-interactieve-website#8]
https://github.com/EBok1/the-startup-responsive-interactieve-website/blob/679a8bcf9858f30e9ddfc1a7282b3997282ac257/index.html#L52

Dit is een error uit de W3C Validatior : 

- Er wordt hier een p element als een child  in een button element gestopt dat mag niet.  
- Ik zou kijken naar andere "lees meer" opties

**Comment by EBok1** [comment]
P element weggehaald uit button.
